const UPDATE_RESPONSE = "UPDATE_RESPONSE";
const UPDATE_FILTERS = "UPDATE_FILTERS";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const UPDATE_PAGE = "UPDATE_PAGE";

export default {
  UPDATE_FILTERS,
  UPDATE_RESPONSE,
  CLEAR_FILTERS,
  UPDATE_PAGE,
};
